add MPTelemetry 1.1 plan review
microprofile/microprofile-wg pull request #187
Opened 2023-05-16 10:41 UTC by Emily-Jiang

2023-06-06 08:22 UTC, Emily-Jiang commented on telemetry/1.1/README.adoc
> +* https://projects.eclipse.org/projects/technology.microprofile/releases/microprofile-telemetry-1.0[MicroProfile Telemetry 1.1 Release Record]
```suggestion
* https://projects.eclipse.org/projects/technology.microprofile/releases/microprofile-telemetry-1.1[MicroProfile Telemetry 1.1 Release Record]
```

2023-06-06 08:28 UTC, Emily-Jiang commented on telemetry/1.1/README.adoc
> +* https://projects.eclipse.org/projects/technology.microprofile/releases/microprofile-telemetry-1.0[MicroProfile Telemetry 1.1 Release Record]
solved

2023-06-14 23:12 UTC, jclingan commented on telemetry/1.1/README.adoc
> +summary: "Release for MicroProfile 6.1"
We haven't committed to the next release being 6.1. I'd leave the summary blank, the same as Config 3.1.

2023-06-14 23:14 UTC, jclingan requested changes
One comment on removing 6.1 platform release target.

2023-06-20 14:47 UTC, jclingan approved these changes

2023-06-20 15:07 UTC, merged